image: bradrydzewski/node:0.10
env:
  - NODE_ENV=development
services:
  - bradrydzewski/mongodb:2.4
script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install --config.interactive=false --allow-root
  - grunt test
